---
:mailboxes:
  -
    :email: <%= ENV['GMAIL_USERNAME'] %>
    :password: <%= ENV['GMAIL_PASSWORD'] %>
    :name: inbox
    :delivery_method: sidekiq
    :delivery_options:
      :redis_url: <%= ENV['REDIS_URL'] || 'redis://127.0.0.1:6379' %>
      :worker: InboundEmailWorker

