development:
  sessions:
    default:
      database: media_manager_development
      hosts:
        - localhost:27017
  options:
    identity_map_enabled: true
test:
  sessions:
    default:
      database: media_manager_test
      hosts:
        - localhost:27017
  options:
    identity_map_enabled: true
